### ISSUE TITLE
error"Exception: No submit queue specified"

### ISSUE THREAD

**Issue by zypiner** [amcpherson/remixt#2]
Hello，

   I  met one problem when I ran remix, the command I executed is that
"
remixt run ref_data_dir result_remix breakpoit/bp.hg19.txt --normal_sample_id oec --normal_bam_file bam/OEC130618.rlg.bam --tumour_sample_ids lm130227 --tumour_bam_files bam/LM130227.rlg.bam --results_files lm130227.hd --tmpdir temp
",

and the error is that:
"
/home/yuzh/miniconda2/lib/python2.7/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools
Traceback (most recent call last):
  File "/home/yuzh/miniconda2/bin/remixt", line 11, in <module>
    load_entry_point('remixt==0.5.5', 'console_scripts', 'remixt')()
  File "/home/yuzh/miniconda2/lib/python2.7/site-packages/remixt/ui/main.py", line 24, in main
    func(**args)
  File "/home/yuzh/miniconda2/lib/python2.7/site-packages/remixt/ui/run.py", line 32, in run
    pyp = pypeliner.app.Pypeline([remixt], pypeliner_config)
  File "/home/yuzh/miniconda2/lib/python2.7/site-packages/pypeliner/app.py", line 195, in __init__
    config_filename=self.config['submit_config'])
  File "/home/yuzh/miniconda2/lib/python2.7/site-packages/pypeliner/execqueue/factory.py", line 6, in create
    raise Exception('No submit queue specified')
Exception: No submit queue specified
“

By the way, the reference genome I used is hg19 instead of GRCh37, I was wondering whether it will have an effect on the result.

I have no idea about how to solve this problem.  I will appreciate it very much if you could help me. 

Thank you!

**Comment by amcpherson** [comment]
Try adding --submit local

**Comment by simozacca** [comment]
I had the same issue and the solution worked when running on a local machine. 

If the expected default behavior is indeed to run on a single multi-core machine, would be possible to make this value `--submit local` as the default one?
